#Daz_activity.py is a text bank for pasta and league of legends references
Daz_activity_options = [r"You could try this cool thing called the FitnessGram Pacer test. The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.",
                "Have you considered playing RAID SHOW LEGENDS? RAID: Shadow Legends™️ is an immersive online experience with everything you'd expect from a brand new RPG title. It's got an amazing storyline, awesome 3D graphics, giant boss fights, PVP battles, and hundreds of never before seen champions to collect and customize. I never expected to get this level of performance out of a mobile game. Look how crazy the level of detail is on these champions! RAID: Shadow Legends™️ is getting big real fast, so you should definitely get in early. Starting now will give you a huge head start. There's also an upcoming Special Launch Tournament with crazy prizes! And not to mention, this game is absolutely free! So go ahead and check out the video description to find out more about RAID: Shadow Legends™️. There, you will find a link to the store page and a special code to unlock all sorts of goodies. Using the special code, you can get 50,000 Silver immediately, and a FREE Epic Level Champion as part of the new players program, courtesy of course of the RAID: Shadow Legends™ devs.",
                       "Life can sometimes be hard. But you know what else is hard? Trying to create your own website. HTML, CSS, PHP, CMS, who has time for that? That's why you need Squarespace. Squarespace is the easy way to create your very own professional website using simple drag and drop actions, no matter if you're trying to open a digital storefront or finally starting that travel blog you were always talking about. If you want to give Squarespace a try, they are currently offering a special promo where you can get your own website, AND your very own domain for a free trial month by registering using the promo code squarespace.com/LifeIsHard. \n\nThat's squarespace.com/LifeIsHard"]

prime = "Hey there! Do you want to know about Twitch Prime? Oh! You may be asking, 'What's Twitch Prime?' Let me tell ya! When you connect your Amazon account to your Twitch account, you can get 1 free sub to ANY streamer on Twitch, every month! Yup, and along with that, get yourself some Twitch loot! With Twitch loot, you can go ahead and get yourself some exclusive Twitch gear and your favorite games! And until April 30th, you can get yourself some Fortnite skins, with Twitch loot! So go ahead! Grab your Amazon account, grab a family or friend's Amazon Prime account, and link it to your Twitch account TODAY!"

throw_pasta_1_1 = "Around 10,000 B.C. humans invented the slinger, to allow them to throw objects even harder\nAround 400 B.C. humans invented the catapult, which allowed them to throw objects even harder.\nShortly after, the Trebuchet followed, which allowed people to throw objects even harder.\nIn 1958 they invented the ICBM, which allowed people to blast objects anywhere on the planet.\nSince then, the evolution of throwing things has mostly been halted, until today when "  

throw_pasta_1_2 = " invented a new way to throw leads harder than was previously imagined possible."

throw_pasta_2_1 = " my son is a huge fan of yours. Anyway over the past few days of watching you play this game hes got much better at playing baseball (he plays in the 11-13 year old division). I just wanted to stop by and thank you for teaching him how to throw so well."

Shakespeare_monkey = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L","M", "N", "O", "P", "Q", "R", "S", "T","U","V", "W", "X", "Y", "Z", "A", "E", "I", "O", "U"]

Rammus = "English: Ok\nAfrikaans: Goed\nAlbanian: Ne rregull\nAmharic: እሺ\nArabic: نعم\nArmenian: Լավ\nAzerbaijani: Tamam\nBulgarian: Добре\nChinese Simplified: 好的\nChinese Traditional: 好的\nEstonian: Okei\nFrench: D'accord\nGreek: Εντάξει\nHebrew: בסדר\nItalian: 🤌\nKorean: 확인\nLithuanian: ठीक आहे\nMalay: Okey\nPolish: Dobrze\nSerbian: У реду\nTamil: சரி\nTurkish: Tamam\nVietnamese: Đồng ý"

Volibear = "#WHAT SHOULD I DO IF I SEE A BEAR? \nSeeing a bear in the wild is a special treat for any visitor to a national park. While it is an exciting moment, it is important to remember that bears in national parks are wild and can be dangerous. Their behavior is sometimes unpredictable. Although rare, attacks on humans have occurred, inflicting serious injuries and death. Each bear and each experience is unique; there is no single strategy that will work in all situations and that guarantees safety. Most bear encounters end without injury. Following some basic guidelines may help to lessen the threat of danger. Your safety can depend on your ability to calm the bear.\nWhen you arrive in a park, always remember to check with the nearest visitor center or backcountry office for the latest bear safety information. \n#AVOIDING AN ENCOUNTER \nFollowing viewing etiquette is the first step to avoiding an encounter with a bear that could escalate into an attack. Keeping your distance and not surprising bears are some of the most important things you can do. Most bears will avoid humans if they hear them coming. Pay attention to your surroundings and make a special effort to be noticeable if you are in an area with known bear activity or a good food source, such as berry bushes \n#BEAR ENCOUNTERS \nOnce a bear has noticed you and is paying attention to you, additional strategies can help prevent the situation from escalating. \nIDENTIFY YOURSELF by talking calmly so the bear knows you are a human and not a prey animal. Remain still; stand your ground but slowly wave your arms. Help the bear recognize you as a human. It may come closer or stand on its hind legs to get a better look or smell. A standing bear is usually curious, not threatening."

Uninstalling_1 = "UNINSTALLING " 

Uninstalling_2 = "\n▇▇▇▇▇▇▇▇▇▇▇▇▇▇▢\n╭━╮╭━╮╭╮　╱\n╰━┫╰━┫╰╯╱╭╮\n╰━╯╰━╯　╱　╰╯\nCOMPLETE"

LunarMan = "I am Lukas Unarman's father and I raised him right and taught him manners and how to be a man. I did not teach him to be tox*c and whiff all his shots. After three straight incidents of his behavior recently, I have disowned him. He is no longer a son of mine. I must urge a boycott of LunarMan79. Come home my boy"

Ake = "I grew up not knowing who my biological father was. When I turned 18 my mother told me his name was Alexander 'Ake' Kekw. When we met, I felt I had found a piece of who I was. I loved him immediately, as if I had known him my whole life and moved in with him.\nWe talked and hung out for the next four months until two weeks ago I told Alex I'm having a rough time entering site. He looked shocked about it, and he said that was ok, and that he was just going to go to the otherside of town and 'lurk' a bit and 'see if he can get a pick' on someone. Nobody has seen him since. If you have seen him, please tell my father to come home, our other duelist is afk and we still can't get onto site."

Eunbi = 'Last week I saw Jung Eunbi while in line at the bank. He was surrounded by 6 (now retired) K Pop idols and a backpack made out of limited edition GFriend light sticks that was donated to him by the agency. I asked how was he so popular. He shouted "WATCH THIS", pulled out a bag of coins and starting throwing $11,615 at the cashier. Then he screeched "RACE YOU TO THE SPIKE SITES!" double updrafted and dashed out of the store...'

Issa = 'So I says to my brother, I says, "Where can I go to find some high level Sage gaming?". He replies, "You should check out Issa on Woolies.TV. She go hard!". I come watch this stream only to find Issa walling her team into a deathpit, rez baiting her friends and complaining Sage should be able to "build" more walls. What a grotasque, lecherous hag my brother is.'

Daiwa = "Daiwa and his Daiwa lived alone in a small Daiwa on an Daiwa. Daiwa kept to himself, drawing Daiwas and playing with his Daiwas as his Daiwa watched Christian Daiwa on the Daiwa. Daiwa was Daiwa, and they were both Daiwa. That was, until Daiwa's Daiwa heard an Daiwa from Daiwa. 'Your Daiwa has become Daiwa by Daiwa, he needs to be Daiwa.' 'I will do my best Daiwa, my Daiwa', she replied, rushing into Daiwa's Daiwa, removing all that was Daiwa from his Daiwa. Again, the Daiwa called Daiwa. 'Daiwa's Daiwa is still Daiwa. He needs to be cut off from all that is Daiwa in his Daiwa and confess his Daiwas.' 'I will follow your Daiwa, I have Daiwa in thee', Daiwa's Daiwa replied, as she locked Daiwa in his Daiwa, away from the Daiwas of the Daiwa. One last Daiwa, Daiwa's Daiwa heard the Daiwa of Daiwa calling to Daiwa. 'You've done as I've asked, but I still question your Daiwa to Daiwa. To prove your Daiwa, I will ask one more Daiwa of Daiwa.' 'Yes, Daiwa, anything.' Daiwa's Daiwa begged. 'To prove your Daiwa in Daiwa, I require Daiwa. Your Daiwa will be the Daiwa. Go into his Daiwa, and end his Daiwa, as an Daiwa to Daiwa to prove you Daiwa me above all Daiwa.' 'Yes, Daiwa', she replied, grabbing an Daiwa from the Daiwa. Daiwa, watching through an Daiwa in his Daiwa, trembled in Daiwa. Scrambling around his Daiwa to find an Daiwa, he noticed an Daiwa to the Daiwa, hidden under his Daiwa. Without Daiwa, he flung open the Daiwa, just as Daiwa burst through his Daiwa, and threw himself down into the unknown Daiwas below."

Nori = "**Nick 'LS' De Cesare, former headcoach of Cloud9**: People that main Nami, yeah I know you're listening. Your ears just perk up? Yeah listen. They're ILL. Okay? They're ill. You hear that? You're ill. Okay. Nami mains come with the most bizarre confidence or something where, I don't even know where it comes from. They're often the dumbest of the enchanter support mains, while simultaneously being the most beta aggressive. Now I don't even know how they accomplished that, but it's true it is true tell me I'm wrong, you can't. And then it's almost like they're playing inebriated because of the speed they cast like their ultimate or their bubble or like everything else it's the weirdest thing. And most of their shit that they do is predicated on just pressing like their enhanced damage ability on the AD carries that usually are paired with them like caitlyn and draven. I don't even know!"

F1 = "Gentlemen, a short view back to the past. Thirty years ago, Niki Lauda told us: 'Take a trained monkey, place him into the cockpit and he is able to drive the car.' Thirty years later Sebastian told us: 'I had to start my car like a computer. It's very complicated.' And Nico Rosbeg said, err, he pressed during the race, I don't remember what race, the wrong button on the wheel. Question for you to both. Is formula 1 driving today too complicated with 20 and more buttons on the wheel, are you too much under effort, under pressure? What are your wishes for the future, concerning technical program, errrm, during the race? Less buttons, more? Or less and more comunication with your engineers."

Grammarly = ["[Coach] My job is to make college easier. Because students have a lot on their...\n-FRISBEE CRASHING-\n[Boy] Sorry coach!\n[Coach] ...plates. Like Harper an Econ Major who piles on the pressure. Grammarly can help her stress less.\n[Harper] This term paper's got to be great. A lot's riding on my grade.\n[Coach] Your ideas are on the money. Let's make sure they come across clearly with Grammarly. Watch it work, watch it work.\n[Harper] Wow, that is stronger.\n[Coach] And Avery, an engineering major who runs on ambition and coffee. Grammarly can get her dream job.\n[Avery] My application needs to stand out. They only meet with the top candidates.\n[Coach] If you want to make a good impression and nail your delivery, use Grammarly. You don't want to pull another all nighter, do you?\n-UPBEAT MUSIC-\n[Coach] Now THAT'S taking it to the end zone. Yeah, oh touch down with Grammarly. And Blake, an Education Major who knows what he wants. So...you're gonna be a school teacher?\n[Blake] Yeah. But first I need to get my senior thesis over the finish line. I keep repeating the same words.\n[Coach] Let Grammarly help you find the right words faster! Grammarly, do your magic. And you did it in one place. Grammarly means better results, that's why it's the writing tool selected by 3,000 schools and universities. Try Grammarly for free by clicking the blue button. Class dismissed. Go on, download Grammarly today. Blue button, right there, Grammarly. Oh yeah, click it. Don't look at us. It's just a coach and a duck, it's all right, you click that blue button. All right, you've seen it before, haven't you? Hahaha...Phew...Grammarly, for the win.",
            "You can help me write my story. But I know what you're thinking: writing's not easy. That's why Grammarly can help. This sentence is grammatically correct, but it's wordy, and hard to read. It undermines the writer's message and the word choice is bland. Grammarly's cutting edge technology helps you craft compelling, understandable writing that makes an impact on your reader. Much better. Are you ready to give it a try? Installation is simple and free. Visit Grammarly.com today!",]

#List of colours that are randomly assigned to embed profiles of users. To change the colour of an embed, change the code in the json file.
colours = ["FF6900", "7BDCB5", "0693E3", "EB144C", "9900EF", "FFEB3B", "795548", "3F51B5", "FFFFFF"]